version: '3.8'

networks:
  traefik:
    external: true

volumes:
  pgadmin_data:

services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - traefik
    environment:
      PGADMIN_DEFAULT_EMAIL: mikegeorgeff3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/root/.pgadmin
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.entrypoints=http"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.georgeff.io`)"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"