version: '3.8'

networks:
  traefik:
    external: true

volumes:
  redisinsight:

services:
  app:
    image: redislabs/redisinsight:latest
    networks:
      - traefik
    volumes:
      - redisinsight:/db
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.redisinsights.entrypoints=http"
        - "traefik.http.routers.redisinsights.rule=Host(`insights.georgeff.io`)"
        - "traefik.http.services.redisinsights.loadbalancer.server.port=8001"
